# Generated by Django 4.2.4 on 2023-08-14 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCodes',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('currency', models.CharField(default=None, max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('from_value', models.FloatField(default=1.0)),
                ('to_currency', models.CharField(max_length=10)),
                ('to_value', models.FloatField(default=1.0)),
                ('conversion', models.FloatField(default=0.0)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
