# Generated by Django 4.2.4 on 2023-08-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_countrycodes_currencyconvert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='code',
        ),
        migrations.AddField(
            model_name='currencies',
            name='currency_code',
            field=models.ForeignKey(default='XXX', on_delete=django.db.models.deletion.CASCADE, to='convert.countrycodes'),
            preserve_default=False,
        ),
    ]
