# Generated by Django 4.2.4 on 2023-08-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0003_remove_currencies_code_currencies_currency_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currencies',
        ),
    ]
