# Generated by Django 4.2.4 on 2023-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0004_delete_currencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyconvert',
            old_name='conversion',
            new_name='to_EUR',
        ),
        migrations.RemoveField(
            model_name='currencyconvert',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='currencyconvert',
            name='to_currency',
        ),
        migrations.RemoveField(
            model_name='currencyconvert',
            name='to_value',
        ),
        migrations.AddField(
            model_name='currencyconvert',
            name='to_GBP',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currencyconvert',
            name='to_JPY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='currencyconvert',
            name='to_USD',
            field=models.FloatField(default=0.0),
        ),
    ]
