# Generated by Django 4.2.4 on 2023-08-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0005_rename_conversion_currencyconvert_to_eur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyconvert',
            name='from_currency',
        ),
        migrations.AddField(
            model_name='currencyconvert',
            name='code',
            field=models.CharField(default='XXX', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyconvert',
            name='currency',
            field=models.CharField(default='currency name', max_length=75),
            preserve_default=False,
        ),
    ]
