# Generated by Django 4.2.4 on 2023-08-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0006_remove_currencyconvert_from_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencyConvert',
            new_name='ExchangeRates',
        ),
    ]
