# Generated by Django 4.2.4 on 2023-08-17 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0007_rename_currencyconvert_exchangerates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_currency', models.CharField(max_length=4)),
                ('output_currency', models.CharField(max_length=4)),
                ('input_value', models.FloatField(default=1.0)),
                ('output_value', models.FloatField(default=0.0)),
                ('conversion', models.FloatField(default=1.0)),
                ('is_converted', models.BooleanField(default=False)),
                ('asked_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
