# Generated by Django 4.2.4 on 2023-08-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0008_currencyconvert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyconvert',
            old_name='is_converted',
            new_name='_is_converted',
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='input_currency',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='output_currency',
            field=models.CharField(max_length=8),
        ),
    ]
