# Generated by Django 4.2.4 on 2023-08-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0009_rename_is_converted_currencyconvert__is_converted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerates',
            name='currency',
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='input_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_code', to='convert.countrycodes'),
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='output_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_code', to='convert.countrycodes'),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.countrycodes'),
        ),
    ]
