# Generated by Django 4.2.4 on 2023-08-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0010_remove_exchangerates_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerates',
            name='currency',
            field=models.CharField(default='no name', max_length=75),
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='input_currency',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='output_currency',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
