# Generated by Django 4.2.4 on 2023-08-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0011_exchangerates_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerates',
            name='code',
        ),
        migrations.RemoveField(
            model_name='exchangerates',
            name='currency',
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convert.countrycodes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerates',
            name='url',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='input_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_code', to='convert.countrycodes'),
        ),
        migrations.AlterField(
            model_name='currencyconvert',
            name='output_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_code', to='convert.countrycodes'),
        ),
    ]
