# Generated by Django 4.2.4 on 2023-08-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0013_alter_currencyconvert_input_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='url',
            field=models.URLField(default='', max_length=250),
        ),
    ]
